Added lookup V2 endpoint + example
experiandataquality/postman-collections pull request #7
Opened 2022-07-29 12:38 UTC by RyapovDimitar

Added lookup V2 endpoint + example

2022-08-01 06:39 UTC, keelimbeh commented on Experian Address Validation.postman_collection.json
> +								"value": "true",
Suggest to add description

2022-08-01 06:42 UTC, keelimbeh commented on Experian Address Validation.postman_collection.json
> +									"raw": "{{baseUrl}}/address/lookup/v1",
should be v2

2022-08-01 06:42 UTC, keelimbeh commented on Experian Address Validation.postman_collection.json
> +										"v1"
should be v2

2022-09-02 16:19 UTC, jbate requested changes
As already mentioned, there appear to be some instances of "v1" appearing in the json.

2022-09-07 08:22 UTC, wnkr approved these changes

2022-09-08 07:50 UTC, RyapovDimitar commented on Experian Address Validation.postman_collection.json
> +								"value": "true",
Added description

2022-09-08 07:50 UTC, RyapovDimitar commented on Experian Address Validation.postman_collection.json
> +										"v1"
Fixed

2022-09-08 07:51 UTC, merged